apiVersion: v1
kind: Pod
metadata:
  name: pods-poc-pod
spec:
  containers:
    - name: collector
      image: pods-poc-collector:latest
      command: ["python","-u","services/collector/collector.py"]
      volumeMounts:
        - name: data
          mountPath: /data
    - name: trend
      image: pods-poc-trend:latest
      command: ["python","-u","services/trend/trend.py"]
      volumeMounts:
        - name: data
          mountPath: /data
    - name: web
      image: pods-poc-web:latest
      command: ["python","-u","services/web/server.py"]
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: data
          mountPath: /data
    - name: storage
      image: pods-poc-storage:latest
      command: ["python","-u","services/db_manager/db_manager.py"]
      volumeMounts:
        - name: data
          mountPath: /data
  restartPolicy: Always
  volumes:
    - name: data
      hostPath:
        path: /srv/pods-poc/data   # <-- CHANGE THIS to your host absolute path
        type: DirectoryOrCreate
