apiVersion: v1
kind: Pod
metadata:
  name: poc-lektrix-pod
spec:
  containers:
    - name: collector
      image: poc-lektrix-collector:latest
      command: ["python","-u","src/collector/collector.py"]
      volumeMounts:
        - name: data
          mountPath: /data
    - name: trend
      image: poc-lektrix-trend:latest
      command: ["python","-u","src/trend/trend.py"]
      volumeMounts:
        - name: data
          mountPath: /data
    - name: web
      image: poc-lektrix-web:latest
      command: ["python","-u","src/web/server.py"]
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: data
          mountPath: /data
    - name: storage
      image: poc-lektrix-storage:latest
      command: ["python","-u","src/db_manager/db_manager.py"]
      volumeMounts:
        - name: data
          mountPath: /data
  restartPolicy: Always
  volumes:
    - name: data
      hostPath:
        path: /srv/poc-lektrix/data   # <-- CHANGE THIS to your host absolute path
        type: DirectoryOrCreate

